![Hand with calculator](calculator.jpg)

Did you know that the average return from investing in stocks is [10% per year](https://www.nerdwallet.com/article/investing/average-stock-market-return) (not accounting for inflation)? But who wants to be average?! 

You have been asked to support an investment firm by analyzing trends in high-growth companies. They are interested in understanding which industries are producing the highest valuations and the rate at which new high-value companies are emerging. Providing them with this information gives them a competitive insight as to industry trends and how they should structure their portfolio looking forward.

You have been given access to their `unicorns` database, which contains the following tables:

## dates
| Column       | Description                                  |
|------------- |--------------------------------------------- |
| `company_id`   | A unique ID for the company.                 |
| `date_joined` | The date that the company became a unicorn.  |
| `year_founded` | The year that the company was founded.       |

## funding
| Column           | Description                                  |
|----------------- |--------------------------------------------- |
| `company_id`       | A unique ID for the company.                 |
| `valuation`        | Company value in US dollars.                 |
| `funding`          | The amount of funding raised in US dollars.  |
| `select_investors` | A list of key investors in the company.      |

## industries
| Column       | Description                                  |
|------------- |--------------------------------------------- |
| `company_id`   | A unique ID for the company.                 |
| `industry`     | The industry that the company operates in.   |

## companies
| Column       | Description                                       |
|------------- |-------------------------------------------------- |
| `company_id`   | A unique ID for the company.                      |
| `company`      | The name of the company.                          |
| `city`         | The city where the company is headquartered.      |
| `country`      | The country where the company is headquartered.   |
| `continent`    | The continent where the company is headquartered. |

# The output

Your query should return a table in the following format:
| industry  | year | num\_unicorns       | average\_valuation\_billions |
| --------- | ---- | ------------------- | ---------------------------- |
| industry1 | 2021 |        ---          |             ---              |
| industry2 | 2020 |        ---          |             ---              |
| industry3 | 2019 |        ---          |             ---              |
| industry1 | 2021 |        ---          |             ---              |
| industry2 | 2020 |        ---          |             ---              |
| industry3 | 2019 |        ---          |             ---              |
| industry1 | 2021 |        ---          |             ---              |
| industry2 | 2020 |        ---          |             ---              |
| industry3 | 2019 |        ---          |             ---              |

Where `industry1`, `industry2`, and `industry3` are the three top-performing industries.

In [2]:
WITH top_industries AS(
	SELECT industries.industry, COUNT(*) AS num_unicorns
	FROM companies
	JOIN industries ON companies.company_id = industries.company_id
	JOIN dates ON companies.company_id = dates.company_id
	WHERE dates.year_founded BETWEEN 2019 AND 2021
	GROUP BY industries.industry
	ORDER BY num_unicorns DESC
	LIMIT 3
)

SELECT ti.industry, d.year_founded AS year, COUNT(*) AS num_unicorns, ROUND(AVG(funding.valuation / 1000000000), 2) AS average_valuation_billions
FROM companies c
JOIN industries ON c.company_id = industries.company_id
JOIN funding ON c.company_id = funding.company_id
JOIN dates d ON c.company_id = d.company_id
JOIN top_industries ti ON industries.industry = ti.industry
WHERE d.year_founded BETWEEN 2019 AND 2021
GROUP BY ti.industry, d.year_founded
ORDER BY d.year_founded DESC, num_unicorns DESC;

                          industry  ...  average_valuation_billions
0                          Fintech  ...                        2.33
1  E-commerce & direct-to-consumer  ...                        1.67
2     Internet software & services  ...                        1.00
3  E-commerce & direct-to-consumer  ...                        1.75
4     Internet software & services  ...                        1.25
5                          Fintech  ...                        1.33
6                          Fintech  ...                        2.42
7     Internet software & services  ...                        2.38
8  E-commerce & direct-to-consumer  ...                        2.75

[9 rows x 4 columns]